version: '3.5'
services:
    node:
        image: node:14.17.5
        working_dir: /app
        volumes:
            - .:/app
            - node-modules:/app/node_modules
        expose:
            - 8080
        ports:
            - 8080:8080
        command: npm run serve

volumes:
  node-modules:
    driver: local
